#!/usr/bin/env node
/**
 * Database setup for Trishulan backend.
 *
 *   node scripts/db-setup.mjs          → full setup (generate + push) for whichever DB is active
 *   node scripts/db-setup.mjs --auto   → used by `predev`: only touches the SQLite fallback;
 *                                        never pushes to Postgres automatically.
 *
 * If DATABASE_URL is set (backend/.env, project-root .env, or real env) → PostgreSQL.
 * Otherwise a SQLite schema is derived from prisma/schema.prisma into prisma/sqlite/schema.prisma
 * (enums → String, Float[]/Json → String JSON) and pushed to prisma/dev.db.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";

const backendDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
dotenv.config({ path: path.join(backendDir, ".env") });
dotenv.config({ path: path.join(backendDir, "..", ".env") });

const auto = process.argv.includes("--auto");
const run = (cmd) => execSync(cmd, { cwd: backendDir, stdio: "inherit", env: process.env });

const mainSchemaPath = path.join(backendDir, "prisma", "schema.prisma");
const sqliteDir = path.join(backendDir, "prisma", "sqlite");
const sqliteSchemaPath = path.join(sqliteDir, "schema.prisma");

function buildSqliteSchema(src) {
  const text = src.replace(/\r\n/g, "\n");

  // Collect enum names, then drop enum blocks.
  const enumNames = new Set([...text.matchAll(/^enum\s+(\w+)\s*\{/gm)].map((m) => m[1]));
  let out = text.replace(/^enum\s+\w+\s*\{[^}]*\}\n?/gm, "");

  out = out.replace(/datasource\s+db\s*\{[^}]*\}/, `datasource db {\n  provider = "sqlite"\n  url      = "file:../dev.db"\n}`);
  out = out.replace(
    /generator\s+client\s*\{[^}]*\}/,
    `generator client {\n  provider = "prisma-client-js"\n  output   = "../../node_modules/.prisma-sqlite/client"\n}`,
  );

  out = out
    .split("\n")
    .map((line) => {
      const m = line.match(/^(\s+)(\w+)(\s+)(\w+)(\[\])?(\?)?(.*)$/);
      if (!m) return line;
      const [, indent, name, gap, type, list, optional = "", rest] = m;
      if (list && ["Float", "Int", "String", "Boolean"].includes(type)) {
        return `${indent}${name}${gap}String${optional} @default("[]")${rest.replace(/@default\([^)]*\)/, "")}`;
      }
      if (type === "Json") return `${indent}${name}${gap}String${optional}${rest}`;
      if (enumNames.has(type) && !list) {
        return `${indent}${name}${gap}String${optional}${rest.replace(/@default\((\w+)\)/, '@default("$1")')}`;
      }
      return line;
    })
    .join("\n");

  return `// AUTO-GENERATED by scripts/db-setup.mjs from ../schema.prisma — do not edit.\n${out}`;
}

if (process.env.DATABASE_URL) {
  if (auto) process.exit(0); // Never auto-push to a real Postgres database.
  console.log("🐘 DATABASE_URL found → PostgreSQL");
  run("npx prisma generate");
  run("npx prisma db push");
  process.exit(0);
}

console.log("🗄️  DATABASE_URL not set → SQLite fallback (prisma/dev.db)");
const sqliteSchema = buildSqliteSchema(readFileSync(mainSchemaPath, "utf8"));
const previous = existsSync(sqliteSchemaPath) ? readFileSync(sqliteSchemaPath, "utf8") : null;
const clientExists = existsSync(path.join(backendDir, "node_modules", ".prisma-sqlite", "client", "index.js"));
const dbExists = existsSync(path.join(backendDir, "prisma", "dev.db"));

if (auto && previous === sqliteSchema && clientExists && dbExists) {
  console.log("   SQLite schema unchanged — skipping.");
  process.exit(0);
}

mkdirSync(sqliteDir, { recursive: true });
writeFileSync(sqliteSchemaPath, sqliteSchema);

// The Postgres client is still generated so TypeScript types match the primary schema.
run("npx prisma generate");
run(`npx prisma generate --schema "${sqliteSchemaPath}"`);
run(`npx prisma db push --skip-generate --schema "${sqliteSchemaPath}"`);
console.log("✅ SQLite fallback ready.");
